/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QaranfelRouteImport } from './routes/qaranfel'
import { Route as IndexRouteImport } from './routes/index'

const QaranfelRoute = QaranfelRouteImport.update({
  id: '/qaranfel',
  path: '/qaranfel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/qaranfel': typeof QaranfelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/qaranfel': typeof QaranfelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/qaranfel': typeof QaranfelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/qaranfel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/qaranfel'
  id: '__root__' | '/' | '/qaranfel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QaranfelRoute: typeof QaranfelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qaranfel': {
      id: '/qaranfel'
      path: '/qaranfel'
      fullPath: '/qaranfel'
      preLoaderRoute: typeof QaranfelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QaranfelRoute: QaranfelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
