/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char1575Char1604Char1602Char1585Char1606Char1601Char1604RouteImport } from './routes/القرنفل'
import { Route as IndexRouteImport } from './routes/index'

const Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route =
  Char1575Char1604Char1602Char1585Char1606Char1601Char1604RouteImport.update({
    id: '/القرنفل',
    path: '/القرنفل',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/القرنفل': typeof Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/القرنفل': typeof Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/القرنفل': typeof Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/القرنفل'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/القرنفل'
  id: '__root__' | '/' | '/القرنفل'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route: typeof Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/القرنفل': {
      id: '/القرنفل'
      path: '/القرنفل'
      fullPath: '/القرنفل'
      preLoaderRoute: typeof Char1575Char1604Char1602Char1585Char1606Char1601Char1604RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route:
    Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
