/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char1575Char1604Char1602Char1585Char1606Char1601Char1604RouteImport } from './routes/القرنفل'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as HerbsRouteImport } from './routes/herbs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HerbsSlugRouteImport } from './routes/herbs.$slug'

const Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route =
  Char1575Char1604Char1602Char1585Char1606Char1601Char1604RouteImport.update({
    id: '/القرنفل',
    path: '/القرنفل',
    getParentRoute: () => rootRouteImport,
  } as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const HerbsRoute = HerbsRouteImport.update({
  id: '/herbs',
  path: '/herbs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HerbsSlugRoute = HerbsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HerbsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/herbs': typeof HerbsRouteWithChildren
  '/vision': typeof VisionRoute
  '/القرنفل': typeof Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route
  '/herbs/$slug': typeof HerbsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/herbs': typeof HerbsRouteWithChildren
  '/vision': typeof VisionRoute
  '/القرنفل': typeof Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route
  '/herbs/$slug': typeof HerbsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/herbs': typeof HerbsRouteWithChildren
  '/vision': typeof VisionRoute
  '/القرنفل': typeof Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route
  '/herbs/$slug': typeof HerbsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/herbs' | '/vision' | '/القرنفل' | '/herbs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/herbs' | '/vision' | '/القرنفل' | '/herbs/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/herbs'
    | '/vision'
    | '/القرنفل'
    | '/herbs/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HerbsRoute: typeof HerbsRouteWithChildren
  VisionRoute: typeof VisionRoute
  Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route: typeof Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/القرنفل': {
      id: '/القرنفل'
      path: '/القرنفل'
      fullPath: '/القرنفل'
      preLoaderRoute: typeof Char1575Char1604Char1602Char1585Char1606Char1601Char1604RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herbs': {
      id: '/herbs'
      path: '/herbs'
      fullPath: '/herbs'
      preLoaderRoute: typeof HerbsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herbs/$slug': {
      id: '/herbs/$slug'
      path: '/$slug'
      fullPath: '/herbs/$slug'
      preLoaderRoute: typeof HerbsSlugRouteImport
      parentRoute: typeof HerbsRoute
    }
  }
}

interface HerbsRouteChildren {
  HerbsSlugRoute: typeof HerbsSlugRoute
}

const HerbsRouteChildren: HerbsRouteChildren = {
  HerbsSlugRoute: HerbsSlugRoute,
}

const HerbsRouteWithChildren = HerbsRoute._addFileChildren(HerbsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HerbsRoute: HerbsRouteWithChildren,
  VisionRoute: VisionRoute,
  Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route:
    Char1575Char1604Char1602Char1585Char1606Char1601Char1604Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
